name: numhask-backprop
version: '0.0.1'
synopsis: See readme.md
description: See readme.md for description.
category: project
author: Tony Day
maintainer: tonyday567@gmail.com
copyright: Tony Day (c) 2017
license: BSD3
github: tonyday567/numhask-backprop
extra-source-files:
  - stack.yaml
default-extensions:
  - NegativeLiterals
  - NoImplicitPrelude
  - OverloadedStrings
  - UnicodeSyntax
ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

dependencies:
  - base >=4.7 && <5
library:
  source-dirs: src
  exposed-modules:
    - NumHask.KTuple
    - NumHask.Wrapped
    - NumHask.Backprop
  dependencies:
    - QuickCheck
    - backprop
    - numhask
    - numhask-prelude
    - numhask-prelude
    - random

executables:
  numhask-backprop:
    main: example.hs
    source-dirs: app
    ghc-options:
      - -funbox-strict-fields
      - -fforce-recomp
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - backprop
      - numhask
      - numhask-backprop
      - numhask-prelude
      - protolude
      - random
tests:
  test:
    main: test.hs
    source-dirs: test
    dependencies:
    - backprop
    - doctest
    - numhask-backprop
    - numhask-prelude
    - tasty
